export const RAW_AETHER_LEVELS = [
  {
    id: 'fractured-vein',
    name: 'Fractured Vein',
    subtitle: 'External break versus hidden oxidation',
    targetLabel: 'Heart Gate',
    sourceId: 'source-core',
    targetId: 'heart-gate',
    concepts: ['resistance', 'diagnostics', 'xray', 'polarity'],
    tools: [
      'multimeter',
      'wireCutter',
      'insulationTool',
      'connectorTool',
      'internalRepairTool',
      'polarityInverter',
      'xrayScanner',
    ],
    objectiveText:
      'Restore flow from Point A to the Heart Gate. You may repair the direct artery or reroute through the superconductive bypass.',
    environment: {
      accent: '#6ff6ff',
      fogColor: '#050513',
      currentColor: '#7ffff8',
      islands: [
        { id: 'left-island', position: [-8, -1.2, 0], scale: [5.6, 1.2, 4.1] },
        { id: 'center-island', position: [0, -1.4, 0], scale: [6.8, 1.4, 4.9] },
        { id: 'bypass-island', position: [2.4, 0.2, -4.3], scale: [4.8, 1.1, 3.2] },
        { id: 'right-island', position: [8, -1.2, 0], scale: [5.6, 1.2, 4.1] },
      ],
    },
    target: {
      requiredPolarity: 'positive',
      requiredVoltage: { min: 8, max: 14 },
      currentWindow: { min: 1.2, max: 4.5 },
    },
    nodes: [
      {
        id: 'source-core',
        label: 'Point A',
        kind: 'source',
        position: [-8, 1.5, 0],
        voltage: 12,
        polarity: 'positive',
        description: 'Primary bio-electric source node.',
      },
      {
        id: 'junction-alpha',
        label: 'Alpha Junction',
        kind: 'junction',
        position: [-4.2, 1.7, 0.2],
      },
      {
        id: 'fracture-mid',
        label: 'Fracture Midpoint',
        kind: 'junction',
        position: [0.3, 1.55, 0.4],
      },
      {
        id: 'bypass-crest',
        label: 'Bypass Crest',
        kind: 'junction',
        position: [0.4, 3.6, -4.1],
      },
      {
        id: 'inverter-pad',
        label: 'Polarity Pad',
        kind: 'inverterPad',
        position: [4.2, 3.1, -3.4],
        supportsTools: ['polarityInverter'],
      },
      {
        id: 'heart-gate',
        label: 'Point B',
        kind: 'target',
        position: [8, 1.5, 0],
        minVoltage: 8,
        maxVoltage: 14,
        currentLimit: 4.5,
      },
    ],
    wires: [
      {
        id: 'spine-feed',
        label: 'Spine Feed',
        from: 'source-core',
        to: 'junction-alpha',
        material: 'copper',
        length: 4.1,
        integrity: 93,
        curve: [[-6.2, 2.5, 0.7]],
      },
      {
        id: 'vein-cut',
        label: 'Vein Cut',
        from: 'junction-alpha',
        to: 'fracture-mid',
        material: 'copper',
        length: 4.4,
        integrity: 42,
        damage: {
          external: ['cutWire', 'burnMarks'],
          internal: [],
        },
        curve: [[-2.1, 2.2, 0.9]],
      },
      {
        id: 'core-oxidized',
        label: 'Core Oxidized',
        from: 'fracture-mid',
        to: 'heart-gate',
        material: 'copper',
        length: 7.8,
        integrity: 58,
        damage: {
          external: [],
          internal: ['oxidation'],
        },
        curve: [[4.2, 2.5, 1.4]],
      },
      {
        id: 'bypass-super-a',
        label: 'Super Bypass A',
        from: 'junction-alpha',
        to: 'bypass-crest',
        material: 'superconductor',
        length: 5.6,
        integrity: 100,
        curve: [[-1.8, 3.1, -2.2]],
      },
      {
        id: 'bypass-super-b',
        label: 'Super Bypass B',
        from: 'bypass-crest',
        to: 'inverter-pad',
        material: 'superconductor',
        length: 4.1,
        integrity: 100,
        nativePolarityFlip: true,
        allowModules: ['polarityInverter'],
        curve: [[2.2, 4.4, -4.5]],
      },
      {
        id: 'bypass-return',
        label: 'Super Return',
        from: 'inverter-pad',
        to: 'heart-gate',
        material: 'superconductor',
        length: 4.8,
        integrity: 100,
        curve: [[6.1, 2.9, -1.5]],
      },
    ],
    optimalSolutions: [
      {
        id: 'repair-artery',
        label: 'Repair the direct artery',
        steps: [
          'Use the connector tool on Vein Cut.',
          'Use X-Ray on Core Oxidized.',
          'Repair Core Oxidized with the internal repair tool.',
        ],
      },
      {
        id: 'super-reroute',
        label: 'Reroute through the superconductive bypass',
        steps: ['Install a polarity inverter on Super Bypass B.'],
      },
    ],
  },
  {
    id: 'attenuation-bloom',
    name: 'Attenuation Bloom',
    subtitle: 'Voltage mismatch, Faraday gap, and fiber conversion',
    targetLabel: 'Stabilizer Bloom',
    sourceId: 'storm-nest',
    targetId: 'stabilizer-bloom',
    concepts: ['resistance', 'diagnostics', 'xray', 'transformer'],
    tools: [
      'multimeter',
      'wireCutter',
      'insulationTool',
      'connectorTool',
      'internalRepairTool',
      'transformerModule',
      'xrayScanner',
    ],
    objectiveText:
      'Bring 18 V source energy down into the 9 V stabilizer window. You can repair the direct aluminum trunk or route across the Faraday gap.',
    environment: {
      accent: '#ffb762',
      fogColor: '#130712',
      currentColor: '#ffd392',
      islands: [
        { id: 'nest-island', position: [-9, -1.3, 0], scale: [6.1, 1.2, 4.5] },
        { id: 'middle-island', position: [-1.5, -1.5, 0.5], scale: [5.4, 1.5, 4.7] },
        { id: 'emitter-island', position: [2.4, 0.2, -3.5], scale: [4.3, 1.1, 3.4] },
        { id: 'receiver-island', position: [6.2, 0.2, -3.5], scale: [4.3, 1.1, 3.4] },
        { id: 'target-island', position: [9, -1.1, 0], scale: [5.8, 1.2, 4.2] },
      ],
    },
    zones: [
      {
        id: 'instability-field',
        label: 'Instability Field',
        type: 'instability',
        multiplier: 1.42,
        affectedWireIds: ['unstable-trunk'],
      },
    ],
    target: {
      requiredPolarity: 'positive',
      requiredVoltage: { min: 8.5, max: 10 },
      currentWindow: { min: 1.1, max: 3.8 },
    },
    nodes: [
      {
        id: 'storm-nest',
        label: 'Point A',
        kind: 'source',
        position: [-8.5, 1.6, 0],
        voltage: 18,
        polarity: 'positive',
      },
      {
        id: 'alpha-bus',
        label: 'Alpha Bus',
        kind: 'junction',
        position: [-4, 1.85, 0.4],
      },
      {
        id: 'emitter-pad',
        label: 'Emitter Pad',
        kind: 'transformerPad',
        position: [1.9, 2.2, -2.8],
        supportsTools: ['transformerModule'],
      },
      {
        id: 'receiver-pad',
        label: 'Receiver Pad',
        kind: 'converterPad',
        position: [6, 2.2, -2.8],
        supportsTools: ['connectorTool'],
      },
      {
        id: 'stabilizer-bloom',
        label: 'Point B',
        kind: 'target',
        position: [8.8, 1.55, 0],
        minVoltage: 8.5,
        maxVoltage: 10,
        currentLimit: 3.8,
      },
    ],
    wires: [
      {
        id: 'source-feed',
        label: 'Source Feed',
        from: 'storm-nest',
        to: 'alpha-bus',
        material: 'copper',
        length: 4.7,
        integrity: 98,
        curve: [[-6.1, 2.7, 0.9]],
      },
      {
        id: 'unstable-trunk',
        label: 'Unstable Trunk',
        from: 'alpha-bus',
        to: 'stabilizer-bloom',
        material: 'aluminum',
        length: 12.6,
        integrity: 61,
        damage: {
          external: ['burnMarks'],
          internal: ['microCracks'],
        },
        allowModules: ['transformerModule'],
        transformerOptions: [9],
        zoneIds: ['instability-field'],
        curve: [[2.2, 2.6, 1.8], [5.8, 2.3, 1.2]],
      },
      {
        id: 'induction-feed',
        label: 'Induction Feed',
        from: 'alpha-bus',
        to: 'emitter-pad',
        material: 'copper',
        length: 7.1,
        integrity: 97,
        allowModules: ['transformerModule'],
        transformerOptions: [9],
        curve: [[-0.8, 3.4, -1.7]],
      },
      {
        id: 'faraday-gap',
        label: 'Faraday Gap',
        from: 'emitter-pad',
        to: 'receiver-pad',
        material: 'superconductor',
        type: 'induction',
        length: 4.1,
        integrity: 100,
        state: {
          connected: true,
        },
        curve: [[4.1, 3.4, -4.6]],
      },
      {
        id: 'fiber-tail',
        label: 'Fiber Tail',
        from: 'receiver-pad',
        to: 'stabilizer-bloom',
        material: 'fiber',
        length: 5.4,
        integrity: 100,
        curve: [[7.2, 2.7, -1.4]],
      },
    ],
    optimalSolutions: [
      {
        id: 'repair-direct',
        label: 'Stabilize the direct aluminum trunk',
        steps: [
          'Use the insulation tool on Unstable Trunk.',
          'Reveal the hidden micro-cracks with X-Ray.',
          'Repair the internal fault.',
          'Install a transformer module on Unstable Trunk.',
        ],
      },
      {
        id: 'gap-reroute',
        label: 'Route through the Faraday gap',
        steps: [
          'Install a transformer on Induction Feed.',
          'Install an induction bridge on Faraday Gap with the connector tool.',
          'Install a converter coupler on Fiber Tail.',
        ],
      },
    ],
  },
  {
    id: 'relay-chorus',
    name: 'Relay Chorus',
    subtitle: 'Logical relays, sequence control, and indirect access',
    targetLabel: 'Resonance Gate',
    sourceId: 'chorus-source',
    targetId: 'resonance-gate',
    concepts: ['diagnostics', 'logicGate', 'xray', 'polarity'],
    tools: [
      'multimeter',
      'wireCutter',
      'connectorTool',
      'internalRepairTool',
      'polarityInverter',
      'xrayScanner',
    ],
    objectiveText:
      'Point B is locked behind logic gates. Solve it either by latching Relay A then Relay B for the AND path, or by opening the service OR branch with corrected polarity.',
    environment: {
      accent: '#8dfb9c',
      fogColor: '#06110a',
      currentColor: '#83ffc1',
      islands: [
        { id: 'source-island', position: [-9, -1.2, 0], scale: [5.9, 1.1, 4.1] },
        { id: 'relay-a-island', position: [-3.5, -0.7, 2.8], scale: [4.2, 1.2, 3.2] },
        { id: 'relay-b-island', position: [-3.5, -0.7, -2.8], scale: [4.2, 1.2, 3.2] },
        { id: 'logic-island', position: [2.8, -0.3, 0], scale: [6.6, 1.4, 4.7] },
        { id: 'service-island', position: [2, 1.1, -4.4], scale: [4.8, 1.1, 3.4] },
        { id: 'target-island', position: [8.8, -1.1, 0], scale: [5.8, 1.2, 4.2] },
      ],
    },
    zones: [
      {
        id: 'chorus-pulse',
        label: 'Chorus Pulse',
        type: 'oscillation',
        amplitude: 0.22,
        speed: 0.9,
        affectedWireIds: ['and-output'],
      },
    ],
    target: {
      requiredPolarity: 'positive',
      requiredVoltage: { min: 7, max: 13 },
      currentWindow: { min: 1.1, max: 4.8 },
    },
    nodes: [
      {
        id: 'chorus-source',
        label: 'Point A',
        kind: 'source',
        position: [-8.5, 1.4, 0],
        voltage: 12,
        polarity: 'positive',
      },
      {
        id: 'split-node',
        label: 'Split Node',
        kind: 'junction',
        position: [-5.1, 1.8, 0],
      },
      {
        id: 'relay-a',
        label: 'Relay A',
        kind: 'sequenceRelay',
        position: [-2.3, 2.6, 2.4],
        sequenceIndex: 1,
      },
      {
        id: 'relay-b',
        label: 'Relay B',
        kind: 'sequenceRelay',
        position: [-2.2, 2.6, -2.4],
        sequenceIndex: 2,
      },
      {
        id: 'service-pad',
        label: 'Service Pad',
        kind: 'inverterPad',
        position: [1.3, 3.4, -4.1],
        supportsTools: ['polarityInverter'],
      },
      {
        id: 'logic-and',
        label: 'AND Gate',
        kind: 'gate',
        gateType: 'AND',
        inputNodeIds: ['relay-a', 'relay-b'],
        position: [2.2, 2.8, 1.2],
      },
      {
        id: 'logic-or',
        label: 'OR Gate',
        kind: 'gate',
        gateType: 'OR',
        inputNodeIds: ['relay-a', 'service-pad'],
        position: [2.6, 2.9, -1.7],
      },
      {
        id: 'resonance-gate',
        label: 'Point B',
        kind: 'target',
        position: [8.6, 1.5, 0],
        minVoltage: 7,
        maxVoltage: 13,
        currentLimit: 4.8,
      },
    ],
    wires: [
      {
        id: 'chorus-feed',
        label: 'Chorus Feed',
        from: 'chorus-source',
        to: 'split-node',
        material: 'copper',
        length: 3.8,
        integrity: 99,
      },
      {
        id: 'relay-a-feed',
        label: 'Relay A Feed',
        from: 'split-node',
        to: 'relay-a',
        material: 'copper',
        length: 4.2,
        integrity: 84,
        curve: [[-3.8, 3.2, 1.6]],
      },
      {
        id: 'relay-b-feed',
        label: 'Relay B Feed',
        from: 'split-node',
        to: 'relay-b',
        material: 'aluminum',
        length: 4.4,
        integrity: 66,
        damage: {
          external: [],
          internal: ['internalFracture'],
        },
        curve: [[-3.8, 3.2, -1.6]],
      },
      {
        id: 'and-input-a',
        label: 'AND Input A',
        from: 'relay-a',
        to: 'logic-and',
        material: 'superconductor',
        length: 4.8,
        integrity: 100,
        curve: [[0.1, 4, 2.6]],
      },
      {
        id: 'and-input-b',
        label: 'AND Input B',
        from: 'relay-b',
        to: 'logic-and',
        material: 'fiber',
        length: 5.4,
        integrity: 100,
        curve: [[0.2, 3.9, -0.2]],
      },
      {
        id: 'service-branch',
        label: 'Service Branch',
        from: 'split-node',
        to: 'service-pad',
        material: 'superconductor',
        length: 6.1,
        integrity: 100,
        nativePolarityFlip: true,
        allowModules: ['polarityInverter'],
        curve: [[-0.6, 4.2, -3.1]],
      },
      {
        id: 'service-output',
        label: 'Service Output',
        from: 'service-pad',
        to: 'logic-or',
        material: 'superconductor',
        length: 3.2,
        integrity: 100,
        curve: [[2.2, 4.1, -3.1]],
      },
      {
        id: 'relay-a-or-feed',
        label: 'Relay A OR Feed',
        from: 'relay-a',
        to: 'logic-or',
        material: 'copper',
        length: 6.4,
        integrity: 90,
        curve: [[0.3, 4.3, 0.4]],
      },
      {
        id: 'and-output',
        label: 'AND Output',
        from: 'logic-and',
        to: 'resonance-gate',
        material: 'copper',
        length: 6.4,
        integrity: 89,
        zoneIds: ['chorus-pulse'],
        curve: [[5.1, 3.3, 1.2]],
      },
      {
        id: 'or-output',
        label: 'OR Output',
        from: 'logic-or',
        to: 'resonance-gate',
        material: 'copper',
        length: 6.1,
        integrity: 92,
        curve: [[5, 3.1, -1.4]],
      },
    ],
    optimalSolutions: [
      {
        id: 'sequence-and',
        label: 'Latch the AND branch',
        steps: [
          'Reveal and repair the hidden fracture in Relay B Feed.',
          'Install a converter coupler on AND Input B.',
          'Activate Relay A, then Relay B in sequence.',
        ],
      },
      {
        id: 'service-or',
        label: 'Use the indirect service branch',
        steps: [
          'Install a polarity inverter on Service Branch.',
          'Activate Relay A to satisfy the OR gate.',
        ],
      },
    ],
  },
];
